name: hello

on:
  push:
    branches:
      - main

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "hello"
  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run date
        run: |
            date
  ls_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run ls -l
        run: |
          ls -l
